SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{68F9603D2E4A32D3}" {
     m_sEntityPrefab "{A3C4D5E6F7001200}Prefabs/Weapons/SprayCan/SprayCan.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68F9603D2E4A313F}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_iSupplyCost 5
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{68F9603D2E4A3139}" {
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59F0753ABE}" {
  }
 }
}